# Generated by Django 4.2 on 2024-03-21 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_browser_app', '0003_alter_bookrow_editions_alter_bookrow_published_year_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ValidatedURL',
        ),
    ]
