# Generated by Django 4.2 on 2024-03-21 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_browser_app', '0004_delete_validatedurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookrow',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='BookRow',
        ),
    ]
