# Generated by Django 4.2 on 2024-03-21 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book_browser_app', '0005_remove_bookrow_author_delete_author_delete_bookrow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='ValidatedUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('url', models.URLField()),
                ('url_text', models.TextField(verbose_name='Url text')),
            ],
            options={
                'verbose_name': 'ValidatedUrl',
                'verbose_name_plural': 'ValidatedUrls',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='BookRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('name', models.CharField(max_length=250, verbose_name='Title')),
                ('rating_avg', models.FloatField(verbose_name='RatingAvg')),
                ('raters', models.CharField(max_length=250, verbose_name='Raters')),
                ('published_year', models.CharField(max_length=4, verbose_name='PublishedYear')),
                ('editions', models.CharField(max_length=250, verbose_name='Editions')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='book_browser_app.author', verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.AddField(
            model_name='author',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authors', to='book_browser_app.validatedurl', verbose_name='Url'),
        ),
    ]
